### ISSUE TITLE
Properly build HTTP Headers coming *from* application

### ISSUE THREAD

**Issue by morphogencc** [MidnightCommercial/midnight-http#2]

**Comment by m1keall1son** [comment]
Why don't we run a dummy server here?  or i can run a server on my machine
or something.  Would that help?

On Tue, Oct 11, 2016 at 2:19 PM, nathan lachenmyer <notifications@github.com

**Comment by morphogencc** [comment]
HTTP Headers have been added, in JSON format!

https://github.com/MidnightCommercial/midnight-HTTP/commit/2fb92c399facf664a1c160c3dbdb3f3ab20e64a0
